### ISSUE TITLE
Draw sub-part of a Image

### ISSUE THREAD

**Issue by Rodot** [Gamebuino/Gamebuino-Meta#18]
It's a question that comes pretty often, right now we can draw to an intermediate image to crop it but it might be nice to have a dedicated function.

**Comment by Sorunome** [comment]
since `Graphics::drawImage` also supports scaling via width/height and i don't see many scenarios where you'd need cropping AND scaling at the same time, i'll make it so that you use either cropping or scaling when drawing an image
