### ISSUE TITLE
Random screen failed init

### ISSUE THREAD

**Issue by Rodot** [Gamebuino/Gamebuino-META#22]
On rare occasions, the screen is all scrambled upon startup or when you change between games. Maybe slower SPI speed during init ?

**Comment by Sorunome** [comment]
i'm not sure that would help much, as that also happens within the bootloader and that one doesn't use DMA to speed up SPI....

**Comment by deshipu** [comment]
You probably just want to add a small delay after reset.

**Comment by Sorunome** [comment]
Reopening because I'm not sure if it is really fixed, please reply if you are still having issues with the latest git version of the library

**Comment by Sorunome** [comment]
@Rodot have you experienced it since the attempted fix? Because i haven't and i haven't heard anyone talk about it, so if it's ok i'll close this then

**Comment by Sorunome** [comment]
seems like it is OK to close this, then
