### ISSUE TITLE
Startup pop sound

### ISSUE THREAD

**Issue by Rodot** [Gamebuino/Gamebuino-META#26]
Few people reported a startup pop sound, not sure if the slow ramp is still active ?
https://gamebuino.com/community/topic/quelques-bricoles-sur-la-meta#c1183
Someone recorded it:
https://www.youtube.com/watch?v=AgP2WkRFrds&feature=youtu.be%E2%80%8B%E2%80%8B%E2%80%8B

**Comment by Sorunome** [comment]
This is only when hard-powering the console?

**Comment by Rodot** [comment]
I asked for more information, I opened the ticket not to forget about it ^^

**Comment by MechanicalPen** [comment]
I get the popping noise when I first turn on the machine, right after 'SD Init... ok!' It doesn't happen again til next power cycle.

**Comment by Sorunome** [comment]
Fixed in https://github.com/Gamebuino/Gamebuino-META/commit/36f6e06a5e6366b2c86a66e7d2cc8d4ad258cdcd
