### ISSUE TITLE
Make palette swapping easier

### ISSUE THREAD

**Issue by Rodot** [Gamebuino/Gamebuino-META#27]
@Sorunome  Many people ask how to swap the palettes, maybe we should add setPalette (to pass a whole palette) and setPaletteColor (to set one color) functions ?
https://gamebuino.com/community/topic/how-can-you-implement-multiple-color-pallets

**Comment by Sorunome** [comment]
I think the issue might just be the lack of documentation.

So, adding that with a tutorial on how to use it could "fix" the issue

Am 15. März 2018 08:35:57 MEZ schrieb "Aurélien Rodot" <notifications@github.com>:

**Comment by Rodot** [comment]
I partially agree, because accessing directly class members is bad, that's why I thought about adding some setters... and the appropriate documentation as well.

**Comment by Sorunome** [comment]
Okay, setter and getter it is.

I'm not sure if adding functions to swap out single colors is a good idea, as the palette may be in flash and thus behave unexpectidly

Am 15. März 2018 09:27:48 MEZ schrieb "Aurélien Rodot" <notifications@github.com>:

**Comment by Rodot** [comment]
I was just expressing my opinion, I think it's cleaner and doesn't add much overhead ?
But if you think it's overkill, it's OK too.
For single color setters, we could check the memory area 🤔 But then, _that_ would be overkill ^^

**Comment by Sorunome** [comment]
> For single color setters, we could check the memory area

wouldn't be needed as flasj writes are discarded anyways.

But yeah, i'm kinda in favour of just a global getter&setter

Am 15. März 2018 09:33:13 MEZ schrieb "Aurélien Rodot" <notifications@github.com>:
