### ISSUE TITLE
Support portrait mode

### ISSUE THREAD

**Issue by Rodot** [Gamebuino/Gamebuino-META#28]
* init gb.display with swapped width/height
* set up gb.tft with 0 rotation instead of 90
* (optionnal) generalize the DMA optimization of any size so we keep the fast refresh even in portrait mode

**Comment by Sorunome** [comment]
this is what i called the constants:
```
const Rotation ROTATION_LEFT = Rotation::left;
const Rotation ROTATION_UP = Rotation::up;
const Rotation ROTATION_RIGHT = Rotation::right;
const Rotation ROTATION_DOWN = Rotation::down;
```
called via `gb.setScreenRotation()` should i call them differently?

Also, i didn't do it as either a thing of tft or as a thing of display as it has to change both things, gb.tft (for actual rotation) and gb.tft (for width/height adjustment)

**Comment by Sorunome** [comment]
done in https://github.com/Gamebuino/Gamebuino-META/commit/78c2604762b9137b5b2e47001a855ea4f28f979e
