### ISSUE TITLE
Seems to be missing a LICENSE file 

### ISSUE THREAD

**Issue by yyyc514** [Gamebuino/Gamebuino-META#38]
No way to know how the code is licensed. Unless I'm missing it?

**Comment by iw4rr10r** [comment]
What about this?
https://github.com/Gamebuino/Gamebuino-META/blob/master/lgpl-3.0.txt

**Comment by yyyc514** [comment]
OMG. :-)

Closing in favor of https://github.com/Gamebuino/Gamebuino-META/pull/39
